Server:
  RunMode: debug
  BaseUrl: http://localhost:8008
  HttpPort: 8008
  ReadTimeOut: 60
  WriteTimeOut: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  ContextTimeout: 60
DATABASE:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: pointer
  CharSet: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: shy-anchovy
  Issuer: archiveofourown
  Expire: 28800
Email:
  Host: smtp.163.com
  Port: 465
  UserName: xxx@163.com
  Password: xxx
  IsSSL: true
  From: Pointer
  To:
    - xxx@qq.com
    - xxx@gmail.com
MQ:
  Username: admin
  Password: admin
  Host: 127.0.0.1:5672
Redis:
  Host: :6379
  Password: admin
  ConnectTimeout: 60
  ReadTimeOut: 10
  WriteTimeOut: 10

