Server:
  RunMode: debug
  HttpPort: 8008
  ReadTimeOut: 60
  WriteTimeOut: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  ContextTimeout: 60
DATABASE:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: archive
  CharSet: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: shyptr
  Issuer: archiveofourown
  Expire: 28800
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 3200828584@qq.com
  Password: muyi2144!
  IsSSL: true
  From: 3200828584@qq.com
  To:
    - 3200828584@qq.com
    - shyptr14@gmail.com

